packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 10080
ignoreScripts: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'chokidar@4.0.3'
  - 'eslint-import-resolver-typescript@3.10.1'
  - 'semver@6.3.1'
